### Data Types and Variables in Python

Data types in Python represent the type or category of data that a variable can store. Python supports various built-in data types, including integers, floating-point numbers, strings, lists, tuples, dictionaries, etc. Variables are used to store and manipulate data in a Python program.

#### Variables:

Variables are named containers used to store data values. They provide a way to label and reference data in a program. In Python, variables do not need to be declared explicitly and their data type is inferred based on the value assigned to them.

**Assigning Values to Variables:**


In [29]:
# Assigning values to variables
x = 10  # Integer
y = 3.14  # Float
name = "Alice"  # String
is_valid = True  # Boolean



Explanation:
- In the above example, values of different data types (integer, float, string, boolean) are assigned to variables `x`, `y`, `name`, and `is_valid`.
- Python variables are case-sensitive, meaning `name` and `Name` are considered different variables.
- Variables can store data of any type, and their data type is determined dynamically based on the value assigned to them.

**Printing Variable Values:**


In [30]:
# Printing variable values
print("x:", x)         # Output: x: 10
print("y:", y)         # Output: y: 3.14
print("name:", name)   # Output: name: Alice
print("is_valid:", is_valid)  # Output: is_valid: True


x: 10
y: 3.14
name: Alice
is_valid: True


Explanation:
- The `print()` function is used to display the values stored in variables `x`, `y`, `name`, and `is_valid`.
- It prints the variable name followed by a colon (:) and the value stored in the variable.

#### Data Types:

Data types in Python define the type of data that a variable can store. Each data type has specific operations and functions associated with it. Python provides various built-in data types, including integers, floating-point numbers, strings, lists, tuples, dictionaries, etc.

**Commonly Used Data Types in Python:**


In [31]:
# Commonly used data types in Python
a = 10             # Integer
b = 3.14           # Float
c = "Hello"        # String
d = [1, 2, 3]      # List
e = (1, 2, 3)      # Tuple
f = {"a": 1, "b": 2}  # Dictionary

# Printing the data types of variables
print("Type of a:", type(a))  # Output: Type of a: <class 'int'>
print("Type of b:", type(b))  # Output: Type of b: <class 'float'>
print("Type of c:", type(c))  # Output: Type of c: <class 'str'>
print("Type of d:", type(d))  # Output: Type of d: <class 'list'>
print("Type of e:", type(e))  # Output: Type of e: <class 'tuple'>
print("Type of f:", type(f))  # Output: Type of f: <class 'dict'>


Type of a: <class 'int'>
Type of b: <class 'float'>
Type of c: <class 'str'>
Type of d: <class 'list'>
Type of e: <class 'tuple'>
Type of f: <class 'dict'>


Explanation:
- In the above example, variables `a`, `b`, `c`, `d`, `e`, and `f` are assigned values of different data types (integer, float, string, list, tuple, dictionary).
- The `type()` function is used to determine the data type of each variable.
- It returns the type of the variable as a class object.

**Conclusion:**

Understanding data types and variables is essential in Python programming as they form the foundation for working with data and performing operations on it.


In [32]:
sum_with_return(10,5)

NameError: name 'sum_with_return' is not defined

### Understanding Data Types in Python

Data types in Python represent the type or category of data that a variable can store. Python supports various built-in data types, each serving a specific purpose. Let's explore some common data types in Python:

#### 1. Numeric Data Types:

- **Integers (`int`):** Integers are whole numbers without any decimal point. They can be positive, negative, or zero.

- **Floating-Point Numbers (`float`):** Floating-point numbers, or floats, are numbers with a decimal point or exponential form.

#### 2. Sequence Data Types:

- **Strings (`str`):** Strings are ordered collections of characters enclosed in single quotes (''), double quotes ("") or triple quotes ('''). They represent textual data.

- **Lists (`list`):** Lists are ordered collections of items separated by commas and enclosed in square brackets ([]). They can contain elements of different data types and are mutable (modifiable).

- **Tuples (`tuple`):** Tuples are ordered collections of items separated by commas and enclosed in parentheses (()). They are similar to lists but are immutable (unchangeable).

#### 3. Mapping Data Type:

- **Dictionaries (`dict`):** Dictionaries are collections of key-value pairs enclosed in curly braces ({ }). Each key is associated with a value, and they are unordered.

#### 4. Set Data Type:

- **Sets (`set`):** Sets are unordered collections of unique items enclosed in curly braces ({ }). They do not allow duplicate elements.

#### 5. Boolean Data Type:

- **Boolean (`bool`):** Boolean represents one of two values: `True` or `False`. It is often used for logical operations and conditions.

#### 6. None Type:

- **None (`NoneType`):** None represents the absence of a value or a null value. It is commonly used to signify that a variable has not been assigned a value yet.


In [5]:
# Numeric Data Types
x = 10          # Integer
y = 3.14        # Float

print("Integer:", x)
print("Float:", y)

# Sequence Data Types
name = "Alice"              # String
numbers_list = [1, 2, 3]    # List
coordinates_tuple = (10, 20)  # Tuple

print("String:", name)
print("List:", numbers_list)
print("Tuple:", coordinates_tuple)

# Mapping Data Type
person = {"name": "Alice", "age": 30, "city": "New York"}  # Dictionary

print("Dictionary:", person)

# Set Data Type
unique_numbers_set = {1, 2, 3, 4, 5}  # Set

print("Set:", unique_numbers_set)

# Boolean Data Type
is_valid = True   # Boolean

print("Boolean:", is_valid)

# None Type
empty_value = None   # None

print("None Type:", empty_value)


Integer: 10
Float: 3.14
String: Alice
List: [1, 2, 3]
Tuple: (10, 20)
Dictionary: {'name': 'Alice', 'age': 30, 'city': 'New York'}
Set: {1, 2, 3, 4, 5}
Boolean: True
None Type: None


### Understanding Dynamic Behavior of Variables in Python

In Python, variables exhibit dynamic behavior, meaning they can change their data type during the execution of the program. Unlike statically typed languages, such as C++ or Java, where the data type of a variable is fixed at compile time, Python allows variables to be assigned values of different data types at runtime.

#### Dynamic Behavior Explained:




In [6]:
# Dynamic Behavior of Variables Example
x = 10          # Integer
print("x:", x)
print("Type of x:", type(x))

x = 3.14        # Float
print("x:", x)
print("Type of x:", type(x))

x = "Hello"     # String
print("x:", x)
print("Type of x:", type(x))

x: 10
Type of x: <class 'int'>
x: 3.14
Type of x: <class 'float'>
x: Hello
Type of x: <class 'str'>


#### Explanation:

In the above example, the variable `x` is initially assigned an integer value (`10`). We then print the value of `x` and its data type using the `type()` function. Afterward, we reassign `x` with a float value (`3.14`) and print its value and data type again. Finally, we assign `x` with a string value (`"Hello"`) and print its value and data type once more.

This demonstrates the dynamic behavior of variables in Python, where the same variable `x` can hold values of different data types at different points in the program execution.


### Managing Data Type Size Dynamically in Python

In Python, the size of a data type is managed dynamically by the interpreter, allowing flexibility in memory allocation based on the value assigned to the variable. Python abstracts away the memory management details, making it convenient for developers to focus on writing code without worrying about memory allocation and deallocation.

#### Using `sys.getsizeof()` Function:



In [11]:

import sys

# Example demonstrating dynamic memory allocation in Python
x = 10
print("Size of x:", sys.getsizeof(x))

x = 10945815802105915812
print("Size of x:", sys.getsizeof(x))

y = "Hello"
print("Size of y:", sys.getsizeof(y))

z = [1, 2, 3]
print("Size of z:", sys.getsizeof(z))


Size of x: 28
Size of x: 36
Size of y: 54
Size of z: 88


#### Explanation:

In the above code snippet, we use the `sys.getsizeof()` function from the `sys` module to determine the size of different data types in Python. We assign values of various data types to variables (`x`, `y`, `z`) and then print their respective sizes.

- For an integer value (`x = 10`), the size may vary depending on the value and the underlying platform.
- For a string value (`y = "Hello"`), the size depends on the length of the string and any additional memory overhead.
- For a list (`z = [1, 2, 3]`), the size depends on the number of elements in the list and any additional memory overhead.

This demonstrates how Python dynamically manages the size of different data types based on their values, allowing efficient memory usage.


### Understanding Numeric Data Types in Python

Numeric data types in Python are used to represent numerical values. There are three main numeric data types in Python:

1. **Integers (`int`):** Integers are whole numbers without any decimal point. They can be positive, negative, or zero.

2. **Floating-Point Numbers (`float`):** Floating-point numbers, or floats, are numbers with a decimal point or exponential form.

3. **Complex Numbers (`complex`):** Complex numbers are numbers with a real and imaginary part represented as `real + imaginaryj`.

#### Python Code:



In [12]:

# Example demonstrating numeric data types in Python
integer_num = 10
float_num = 3.14
complex_num = 2 + 3j

print("Integer Number:", integer_num)
print("Type of Integer Number:", type(integer_num))

print("Floating-Point Number:", float_num)
print("Type of Floating-Point Number:", type(float_num))

print("Complex Number:", complex_num)
print("Type of Complex Number:", type(complex_num))

Integer Number: 10
Type of Integer Number: <class 'int'>
Floating-Point Number: 3.14
Type of Floating-Point Number: <class 'float'>
Complex Number: (2+3j)
Type of Complex Number: <class 'complex'>


#### Explanation:

In the provided Python code, we declare variables representing different numeric data types:

- `integer_num` holds an integer value (`10`).
- `float_num` holds a floating-point value (`3.14`).
- `complex_num` holds a complex number value (`2 + 3j`).

We then print the values of these variables along with their respective data types using the `type()` function.

This demonstrates how numeric data types in Python can represent various numerical values, including integers, floating-point numbers, and complex numbers.


### Understanding Boolean Data Type in Python

Boolean data type in Python is used to represent logical values. There are two boolean values in Python: `True` and `False`. They are often used for logical operations and conditions.

#### Python Code:




In [14]:

# Example demonstrating boolean data type in Python
is_valid = True
is_greater_than_10 = False

print("is_valid:", is_valid)
print("Type of is_valid:", type(is_valid))

print("is_greater_than_10:", is_greater_than_10)
print("Type of is_greater_than_10:", type(is_greater_than_10))

is_valid: True
Type of is_valid: <class 'bool'>
is_greater_than_10: False
Type of is_greater_than_10: <class 'bool'>


#### Explanation:

In the provided Python code, we declare variables representing boolean values:

- `is_valid` is assigned the boolean value `True`.
- `is_greater_than_10` is assigned the boolean value `False`.

We then print the values of these variables along with their respective data types using the `type()` function.

Boolean values in Python are stored internally as integers: `True` is represented as `1` and `False` as `0`. This allows boolean values to be used in arithmetic operations, where `True` behaves like `1` and `False` behaves like `0`.

This demonstrates how boolean data type in Python represents logical values and is stored internally as `1` for `True` and `0` for `False`.


### Understanding String Data Type in Python

String data type in Python is used to represent textual data. Strings are sequences of characters, and they can be enclosed in single quotes (''), double quotes (" "), or triple quotes (''' ''' or """ """). Strings can contain letters, numbers, symbols, and spaces.

#### ASCII and Unicode:

ASCII (American Standard Code for Information Interchange) is a character encoding standard that represents characters using 7-bit binary numbers. It can represent a total of 128 characters, including uppercase and lowercase English letters, digits, punctuation symbols, and control characters.

Unicode is a character encoding standard that aims to represent every character in every language in a consistent manner. It uses variable-length encoding and can represent over a million characters. Unicode supports characters from various scripts, including Latin, Greek, Cyrillic, Chinese, Japanese, Korean, and many others.

#### Python Code:




In [15]:

# Example demonstrating string data type in Python
single_quoted_str = 'Hello, World!'
double_quoted_str = "Python Programming"
triple_quoted_str = '''This is a multi-line
string in Python'''
unicode_str = '你好，世界！'

print("Single-Quoted String:", single_quoted_str)
print("Type of Single-Quoted String:", type(single_quoted_str))

print("Double-Quoted String:", double_quoted_str)
print("Type of Double-Quoted String:", type(double_quoted_str))

print("Triple-Quoted String:", triple_quoted_str)
print("Type of Triple-Quoted String:", type(triple_quoted_str))

print("Unicode String:", unicode_str)
print("Type of Unicode String:", type(unicode_str))

Single-Quoted String: Hello, World!
Type of Single-Quoted String: <class 'str'>
Double-Quoted String: Python Programming
Type of Double-Quoted String: <class 'str'>
Triple-Quoted String: This is a multi-line
string in Python
Type of Triple-Quoted String: <class 'str'>
Unicode String: 你好，世界！
Type of Unicode String: <class 'str'>


#### Explanation:

In the provided Python code, we define strings using different quotation styles:

- `single_quoted_str` is enclosed in single quotes ('Hello, World!').
- `double_quoted_str` is enclosed in double quotes ("Python Programming").
- `triple_quoted_str` is enclosed in triple quotes ('''This is a multi-line string in Python''').
- `unicode_str` contains Unicode characters ('你好，世界！').

We print the values of these strings along with their respective data types using the `type()` function.

The use of single, double, or triple quotes allows flexibility in defining strings, especially when dealing with special characters, multiline strings, or strings containing quotes.

This demonstrates how string data type in Python represents textual data and the different ways to define strings using single, double, or triple quotes.


### Accessing Single Character in a String and Understanding Indexing

In Python, you can access a single character in a string by using indexing. Each character in a string has a corresponding index, starting from `0` for the first character. You can use positive indexing to access characters from the beginning of the string and negative indexing to access characters from the end of the string.

#### Python Code:




In [16]:

# Example demonstrating accessing single character in a string and indexing
word = "Python"

# Accessing single character using positive indexing
first_char = word[0]
second_char = word[1]
last_char = word[-1]

print("First Character:", first_char)
print("Second Character:", second_char)
print("Last Character:", last_char)

First Character: P
Second Character: y
Last Character: n


#### Explanation:

In the provided Python code, we have a string `word` containing the word "Python", which has six characters.

- To access the first character, we use positive indexing (`word[0]`), which returns `'P'`.
- To access the second character, we use positive indexing (`word[1]`), which returns `'y'`.
- To access the last character, we use negative indexing (`word[-1]`), which returns `'n'`.

Indexing in Python starts from `0`, so the first character is at index `0`, the second character is at index `1`, and so on. Negative indexing starts from `-1`, where `-1` represents the last character, `-2` represents the second last character, and so on.

This demonstrates how to access a single character in a string using indexing and explains the concept of positive and negative indexing in Python.


### Understanding Indexing in Strings in Python

In Python, indexing allows you to access individual characters within a string. Each character in a string has a corresponding index, which represents its position in the string. Python uses zero-based indexing, where the first character of the string is at index `0`, the second character is at index `1`, and so on.

#### Positive Indexing:

Positive indexing refers to accessing characters from the beginning of the string using positive integers as indices. To access a character at a specific position, you specify its index within square brackets `[ ]`.

For example, in the string `"Python"`:
- The character `'P'` is at index `0`.
- The character `'y'` is at index `1`.
- The character `'t'` is at index `2`.
- And so on.

#### Negative Indexing:

Negative indexing refers to accessing characters from the end of the string using negative integers as indices. The last character of the string has an index of `-1`, the second last character has an index of `-2`, and so on.

For example, in the string `"Python"`:
- The character `'n'` is at index `-1`.
- The character `'o'` is at index `-2`.
- The character `'h'` is at index `-3`.
- And so on.



In [18]:
#### Python Code:

# Example demonstrating positive and negative indexing in strings
word = "Python"

# Positive indexing
first_char = word[0]
second_char = word[1]
last_char = word[-1]

print("First Character (Positive Indexing):", first_char)
print("Second Character (Positive Indexing):", second_char)
print("Last Character (Negative Indexing):", last_char)


First Character (Positive Indexing): P
Second Character (Positive Indexing): y
Last Character (Negative Indexing): n


#### Explanation:

In the provided Python code, we define a string `word` containing the word "Python". We then demonstrate positive and negative indexing to access characters within the string.

- Positive indexing (`word[0]`, `word[1]`) accesses characters from the beginning of the string.
- Negative indexing (`word[-1]`) accesses characters from the end of the string.

Understanding indexing is crucial as it allows you to manipulate and extract substrings from strings effectively. Positive indexing starts from `0`, while negative indexing starts from `-1`, where `-1` represents the last character.

This concept is fundamental in Python and is extensively used in various string operations and data manipulation tasks.


### Understanding Typecasting in Python

Typecasting, also known as type conversion, is the process of converting one data type into another. Python allows both explicit and implicit typecasting.

#### Explicit Typecasting:

Explicit typecasting, also known as forced typecasting, involves converting a variable from one data type to another explicitly using built-in functions or constructors. This type of typecasting requires the programmer to specify the desired data type.

#### Implicit Typecasting:

Implicit typecasting, also known as automatic typecasting, occurs automatically when Python converts one data type to another without the need for explicit instructions from the programmer. Python performs implicit typecasting based on the context of the operation being performed.

#### Python Code:

```python



In [20]:
# Example demonstrating explicit and implicit typecasting in Python
# Explicit typecasting (int to float)
num_int = 10
num_float = float(num_int)

# Implicit typecasting (int to string)
num_int = 10
num_str = "Number: " + str(num_int)

print("Explicit Typecasting (int to float):", num_float)
print("Implicit Typecasting (int to string):", num_str)

Explicit Typecasting (int to float): 10.0
Implicit Typecasting (int to string): Number: 10


#### Explanation:

In the provided Python code, we demonstrate both explicit and implicit typecasting:

- Explicit Typecasting: We convert an integer (`num_int`) to a float using the `float()` constructor. This converts the integer `10` to a floating-point number `10.0`.

- Implicit Typecasting: We concatenate the integer `10` with a string `"Number: "` using the `+` operator. Since the integer `10` is being combined with a string, Python automatically converts it to a string, resulting in the string `"Number: 10"`.

Understanding typecasting is essential for manipulating data and performing operations involving different data types. Explicit typecasting provides control over conversions, while implicit typecasting simplifies operations by automatically converting data types as needed.


In [27]:
# Implicit Typecasting in Python

# Example 1: Integer to Float
num_int = 10
num_float = num_int + 0.5  # Integer implicitly converted to float
print("Result of implicit typecasting (int to float):", num_float)


# Example 3: Boolean to Integer
bool_val = True
num_int = bool_val + 5  # Boolean implicitly converted to integer (True becomes 1)
print("Result of implicit typecasting (boolean to integer):", num_int)


# Example 5: Integer to Boolean
num_int = 0
bool_val = num_int or True  # Integer implicitly converted to boolean (0 becomes False)
print("Result of implicit typecasting (integer to boolean):", bool_val)


Result of implicit typecasting (int to float): 10.5
Result of implicit typecasting (int to string): Number: 10
Result of implicit typecasting (boolean to integer): 6
Result of implicit typecasting (integer to boolean): True


In [28]:

# Explicit Typecasting in Python

# Example 1: String to Integer
num_str = "10"
num_int = int(num_str)  # String explicitly converted to integer
print("Result of explicit typecasting (string to integer):", num_int)

# Example 2: Float to String
num_float = 3.14
num_str = str(num_float)  # Float explicitly converted to string
print("Result of explicit typecasting (float to string):", num_str)

# Example 3: Integer to Float
num_int = 10
num_float = float(num_int)  # Integer explicitly converted to float
print("Result of explicit typecasting (integer to float):", num_float)

# Example 4: String to Boolean
bool_str = "True"
bool_val = bool(bool_str)  # String explicitly converted to boolean
print("Result of explicit typecasting (string to boolean):", bool_val)

# Example 5: Boolean to Integer
bool_val = True
num_int = int(bool_val)  # Boolean explicitly converted to integer
print("Result of explicit typecasting (boolean to integer):", num_int)

# Example 2: Integer to String (Concatenation)
num_int = 10
num_str = "Number: " + str(num_int)  # Integer implicitly converted to string
print("Result of implicit typecasting (int to string):", num_str)


Result of explicit typecasting (string to integer): 10
Result of explicit typecasting (float to string): 3.14
Result of explicit typecasting (integer to float): 10.0
Result of explicit typecasting (string to boolean): True
Result of explicit typecasting (boolean to integer): 1
Result of implicit typecasting (int to string): Number: 10
